name: Firebase Reservation Watcher

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Check reservations
        run: |

          RESPONSE=$(curl -s "https://firestore.googleapis.com/v1/projects/ecurie-paddock/databases/(default)/documents/reservations")

          if [ -n "$RESPONSE" ]; then

            echo "reservation detected"

            curl --request POST \
            --url https://onesignal.com/api/v1/notifications \
            --header "Content-Type: application/json" \
            --header "Authorization: Basic os_v2_app_waemo7qbx5aapjdw6nstnakjtkmyjey5bg2eng43r6hl5v36oc4bfpnq5tyknltlzfmasdm3gioinri2yemutmhkzc6vqxzizu6273q" \
            --data '{
              "app_id": "b008c77e-01bf-4007-a476-f3653681499a",
              "included_segments": ["Subscribed Users"],
              "headings": {"en": "🐎 Paddock"},
              "contents": {"en": "Activité détectée"}
            }'

          fi